apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "innovation-hub.fullname" . }}-config
  labels:
    {{- include "innovation-hub.labels" . | nindent 4 }}
data:
  HOST: {{ .Values.env.HOST | quote }}
  PORT: {{ .Values.env.PORT | quote }}
  DEBUG: {{ .Values.env.DEBUG | quote }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  AI_MODEL: {{ .Values.env.AI_MODEL | quote }}
  OPENROUTER_BASE_URL: {{ .Values.env.OPENROUTER_BASE_URL | quote }}
